version: 2.1

jobs:
  build-and-run-unit-tests:
    # Primary container image where all commands run
    docker:
      - image: cimg/elixir:1.13.3
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/my_app_test
    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"

    steps:
      - checkout:
          path: "/home/circleci/project/app_directory"
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run:
          name: Run Application Unit Tests
          command:  cd app_directory &&
                    mix local.rebar --force &&
                    mix local.hex --force &&
                    mix deps.get &&
                    MIX_ENV=test mix ecto.reset  && mix test
      - run:
          name: Formatted Code
          command:  cd app_directory && mix format --check-formatted